// Renders stored entries as markdown for the per-user `uNNN_daily_log.md`
// file. Works from a saved entry object alone (not live screen state), so the
// whole log can be rebuilt from IndexedDB at sync time.

import { SCHEMA, MOOD_WORDS, ALWAYS_ON, CONDITIONAL, NONE_MARKERS } from "./schema.js";

function pick(pair, lang) {
  if (pair === undefined || pair === null) return "";
  const parts = String(pair).split("||");
  return lang === "zh" ? (parts[0] || "") : (parts[1] !== undefined ? parts[1] : parts[0]);
}

function getActiveDetails(field, value) {
  if (field.detailsByValue) {
    if (Array.isArray(value)) {
      for (const key of Object.keys(field.detailsByValue)) {
        if (value.includes(key)) return field.detailsByValue[key];
      }
      return null;
    }
    return field.detailsByValue[value] || null;
  }
  if (!field.details) return null;
  const t = field.detailsTrigger;
  let visible;
  if (t === "always") visible = value !== null && value !== undefined && value !== "";
  else if (t === "any") {
    const excl = field.excludeValues || [];
    visible = Array.isArray(value) ? value.some((v) => !excl.includes(v)) : (!!value && !excl.includes(value));
  } else {
    visible = Array.isArray(value) ? value.includes(t) : value === t;
  }
  return visible ? field.details : null;
}

function summarizeDetail(dv, lang) {
  if (dv === undefined || dv === "" || (Array.isArray(dv) && dv.length === 0)) return null;
  return Array.isArray(dv) ? dv.map((x) => pick(x, lang)).join("、") : pick(dv, lang);
}

function sectionOrder(entry) {
  const phase = (entry.answers && entry.answers.meta && entry.answers.meta.cyclePhase) || "";
  const cond = CONDITIONAL.filter((id) => SCHEMA[id].condition(phase));
  return ALWAYS_ON.concat(cond);
}

export function entryToMarkdown(entry, lang = "zh") {
  const answers = entry.answers || {};
  const meta = answers.meta || {};
  const lines = [`## ${entry.date}`, ""];

  if (meta.moodRating) {
    lines.push(`- ${pick("整體感覺||Overall mood", lang)}: ${pick(MOOD_WORDS[meta.moodRating - 1], lang)}`);
  }
  if (meta.cyclePhase) {
    lines.push(`- ${pick("週期狀態||Cycle phase", lang)}: ${pick(meta.cyclePhase, lang)}`);
  }
  if (meta.moodRating || meta.cyclePhase) lines.push("");

  sectionOrder(entry).forEach((secId) => {
    const sec = SCHEMA[secId];
    const ans = answers[secId] || {};
    const secLines = [];
    sec.fields.forEach((f) => {
      const v = ans[f.id];
      const other = ans[f.id + "__other"];
      const hasValue = !(v === undefined || v === "" || (Array.isArray(v) && v.length === 0));
      if (!hasValue && !other) return;
      let line = `- ${pick(f.label, lang)}: ` +
        (hasValue ? (Array.isArray(v) ? v.map((x) => pick(x, lang)).join("、") : pick(v, lang)) : "");
      const details = getActiveDetails(f, v);
      if (details) {
        const parts = details.map((d) => {
          const s = summarizeDetail(ans[f.id + "__" + d.id], lang);
          return s ? `${pick(d.label, lang)}: ${s}` : null;
        }).filter(Boolean);
        if (parts.length) line += `（${parts.join("；")}）`;
      }
      if (f.type === "multi" && f.perItemSeverity) {
        const sev = (v || []).filter((x) => !NONE_MARKERS.includes(x)).map((x) => {
          const s = summarizeDetail(ans[f.id + "__sev__" + encodeURIComponent(x)], lang);
          return s ? `${pick(x, lang)}: ${s}` : null;
        }).filter(Boolean);
        if (sev.length) line += `（${sev.join("；")}）`;
      }
      if (other) line += `${hasValue ? "；" : ""}${pick("其他||other", lang)}: ${other}`;
      secLines.push(line);
    });
    if (secLines.length) {
      lines.push(`### ${pick(sec.title, lang)}`, ...secLines, "");
    }
  });

  if (entry.amended) lines.push(`_${pick("此日紀錄含補記內容||This day includes retroactive amendments", lang)}_`, "");
  return lines.join("\n");
}

export function buildUserMarkdown(entries, userId, lang = "zh") {
  const sorted = entries.slice().sort((a, b) => (a.date < b.date ? -1 : 1));
  const header = [
    `# ${userId} — ${lang === "zh" ? "每日中醫日記" : "Daily TCM Log"}`,
    "",
    `_${lang === "zh" ? "由 TCM Tracker 應用程式自動產生，最後更新" : "Generated by the TCM Tracker app, last updated"}: ${new Date().toISOString()}_`,
    `_${lang === "zh" ? "紀錄天數" : "Days logged"}: ${sorted.length}_`,
    "",
    "---",
    "",
  ];
  return header.concat(sorted.map((e) => entryToMarkdown(e, lang))).join("\n");
}
